name: entao_lint
description: dart/flutter lint.
version: 1.0.1
repository: https://github.com/yangentao/entao_lint
homepage: https://github.com/yangentao/entao_lint

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
